_wandb:
    value:
        cli_version: 0.21.1
        code_path: code/notebooks/unit8/ppo.py
        e:
            ie27har8qk5r899mg1oag74koszequyg:
                args:
                    - -tr
                codePath: notebooks/unit8/ppo.py
                codePathLocal: ppo.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "93579317248"
                email: miquelgc2003@gmail.com
                executable: /home/mique/Desktop/Code/deep-rl-class/notebooks/unit8/venv-u8/bin/python
                git:
                    commit: f8ed470f837e96d11b86d84cc03d9d0be1dc0042
                    remote: git@github.com:huggingface/deep-rl-class.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-1046b913-ae16-5ca5-d639-f20e7322867f
                host: Pac
                memory:
                    total: "8185561088"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/mique/Desktop/Code/deep-rl-class/notebooks/unit8/ppo.py
                python: CPython 3.10.18
                root: temp/wandb
                startedAt: "2025-08-17T15:27:44.595559Z"
                writerId: ie27har8qk5r899mg1oag74koszequyg
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
TEMP:
    value: temp
VIDEOS:
    value: videos
cuda:
    value: true
device:
    value: null
exp_name:
    value: ppo
fps:
    value: 30
gym_id:
    value: CartPole-v1
learning_rate:
    value: 0.00025
record_video:
    value: false
runs_path:
    value: temp/runs
seed:
    value: 42
torch_deterministic:
    value: true
total_timesteps:
    value: 25000
track_run:
    value: true
wandb_entity:
    value: null
wandb_path:
    value: temp/wandb
wandb_project_name:
    value: RL
